sudo: required
dist: trusty
language: python
matrix:
  include:
    - python: 3.5
notifications:
  email: false
addons:
  apt_packages:
    - pandoc
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install libopenblas-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION ipython numpy scipy pytest matplotlib mkl mkl-service sphinx
  - source activate testenv
  - pip install travis-sphinx nbsphinx
  - export PATH=$HOME/.local/bin:$PATH
  - pip install pep8 pytest-pep8 python-coveralls pytest-cov
  - pip install sphinxcontrib-napoleon sphinx_rtd_theme
  - pip install theano
  - echo -e "\n[blas]\nldflags = -lopenblas\n" >> ~/.theanorc
  - python setup.py install
script:
  - PYTHONPATH=$PWD:$PYTHONPATH pytest --cov=delfi;
  - travis-sphinx build -n -s docs/
after_success:
  - coveralls
  - travis-sphinx deploy
