``inference`` – Inference algorithms
------------------------------------

Inference algorithms are implemented in the inference submodule. At the moment,
the following algorithms are implemented: 

Basic
`````
.. autoclass:: delfi.inference.Basic
  :show-inheritance:
  :inherited-members:
  :members:

SNPE-A
``````
.. autoclass:: delfi.inference.SNPEA
  :show-inheritance:
  :inherited-members:
  :members:

SNPE-B
``````
.. autoclass:: delfi.inference.SNPEB
  :show-inheritance:
  :inherited-members:
  :members:

APT
``````
.. autoclass:: delfi.inference.APT
  :show-inheritance:
  :inherited-members:
  :members:
