``kernel`` – Kernel functions
-----------------------------

Inference algorithms may utilize kernels as part of the loss function.

Epanechnikov
````````````
.. autoclass:: delfi.kernel.Epanechnikov
  :show-inheritance:
  :inherited-members:
  :members:

Gauss
```````
.. autoclass:: delfi.kernel.Gauss
  :show-inheritance:
  :inherited-members:
  :members:

Tricube
```````
.. autoclass:: delfi.kernel.Tricube
  :show-inheritance:
  :inherited-members:
  :members:

Uniform
```````
.. autoclass:: delfi.kernel.Uniform
  :show-inheritance:
  :inherited-members:
  :members:
