``neuralnet`` – Neural networks
-------------------------------

At the core of density estimation by likelihood-free inference are neural
networks that are used as flexible density estimations (mixture
density networks). These are implemented in ``delfi.neuralnet``.

Neural Network
``````````````
.. autoclass:: delfi.neuralnet.NeuralNet.NeuralNet
  :show-inheritance:
  :inherited-members:
  :members:

Trainer
```````
.. autoclass:: delfi.neuralnet.Trainer.Trainer
  :show-inheritance:
  :inherited-members:
  :members:
